//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depreciacion
    {
        public int IdDepreciacion { get; set; }
        public int Activo { get; set; }
        public System.DateTime FechaDepreciacion { get; set; }
        public double MontoDepreciacion { get; set; }
        public double Valor { get; set; }
    
        public virtual Activos Activos { get; set; }
    }
}
