//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THReparaciones
    {
        public int IdReparacion { get; set; }
        public Nullable<int> IdActivo { get; set; }
        public Nullable<System.DateTime> FechaInicialReparacion { get; set; }
        public Nullable<System.DateTime> FechafinalReparacion { get; set; }
    
        public virtual Activos Activos { get; set; }
    }
}
